### PR TITLE
Update to ember-cli@2.15.0-beta.2 blueprint.

### PR DESCRIPTION
**Pull request by rwjblue**
FYI - This will be a breaking change release (as it drops support for Node < 4).

### CODE REVIEW

**Comment by kimroen** [comment]
Thanks a bunch, Robert 👍

**Comment by Turbo87** [comment]
@kimroen would you have time to do a release in the next days including this change?

**Comment by kimroen** [comment]
@Turbo87 Unfortunately releasing master is slightly blocked by https://github.com/kimroen/ember-cli-document-title/pull/62 at the moment. My bad - I merged a thing before it was ready and now people are pointing at master to use that feature so I can’t just revert it.

Any help there would be appreciated if you have a moment - I doubt I’ll have the energy to look at it before this weekend.

**Comment by Turbo87** [comment]
hmm... would it be possible to release a `v0.4.0` just including this PR and then do the fastboot stuff at a later point? I'm unfortunately not that experienced with fastboot yet but the test doesn't look that bad to me 🤔

**Comment by kimroen** [comment]
@Turbo87 I'm certainly going to look at it. Is there a reason I should know about why you want this released soon? ✨

**Comment by Turbo87** [comment]
I'm trying to get rid of `ember-cli-shims` in a few of our apps and one requirement for that is that all addons use `ember-cli-babel@6` or above. This PR seems to upgrade that dependency :)

**Pull request merged**
