### PR TITLE
Add support for promise titleTokens

### LINKED ISSUE #42: Title token using an async relationship
Hi there! First off, thanks a lot for this great add-on. I've been using it for a while and just found out a (minor) issue.

I have a `models/foo.js` with an `async` relationship to a `user` such as:

```
export default DS.Model.extend({
  title: DS.attr('string'),
  user: DS.belongsTo('user', { async: true })
});
```

In my `routes/foo.js` I have the following `titleToken`:

```
export default Ember.Route.extend({
  titleToken(model) {
    return model.get('user.firstName');
  }
});
```

Because `user`is async, `user.firstName`is `undefined` at this point (`user` is still a `Promise`). When the promise is resolved, the title does not recompute so my title stays empty.

Would you have any recommendation about how to circumvent this issue? Thanks!

### PR DESCRIPTION
**Pull request by poohitan**
In this pull request I want to resolve #42. 

It will be possible to return a promise from `titleToken()` function. Document title will be unset until all promises from tokens chain will be resolved.

### CODE REVIEW

**Comment by poohitan** [comment]
@kimroen can you please check it?

**Comment by kimroen** [comment]
Thank you very much for looking at this - this is promising (no pun intended).

Would you mind adding a test verifying that having the `titleToken` function return a promise works?

Thanks!

**Comment by poohitan** [comment]
Yes, I will add a test a bit later, sorry.

**Comment by poohitan** [comment]
Added a test. Please check.

**Comment by Duder-onomy** [comment]
@kimroen Do you think this will be merged and a new release created any time soon? 
We are pulling from @poohitan 's fork right now and would like to point back at this repo eventually.

**Comment by kimroen** [comment]
@duder-onomy I'm not sure when I'll be able to get this in, but some things I'd love to have someone check and confirm:

- Does the route loading wait for the promise returned from the `titleToken` before rendering the page?
- Do async title tokens work with FastBoot?

**Comment by Duder-onomy** [comment]
@kimroen 

I cannot speak to FastBoot as I dont have that setup for any apps yet, 
BUT! Adding promise support for titleToken does not block the page render,
I pulled down @poohitan's fork and took this gif, notice the page renders, then the title changes 3 seconds later:
ember-cli-document-title promise title token does not block render

As added evidence, TheDyrt.com (decently big Ember app) uses @poohitan's fork right now in production with no issues if that is any consolation.

**Comment by poohitan** [comment]
@kimroen I can't say anything about FastBoot, but I can confirm what @Duder-onomy said. Page doesn't wait for `titleToken` to resolve before rendering.

**Comment by Duder-onomy** [comment]
Just wanted to follow up here. 
@kimroen For this to work nice with fastboot ( and I assume, get merged) , would we need to block render while the promise is unresolved?

**Comment by Duder-onomy** [comment]
@kimroen I have to hound you. But do you know what it would take to get this working with fastboot how you expect it to? I suspect we need to block the fastboot render? I am not using fastboot at work, so I am not sure as to the expectations. 
Anyhow, I keep getting tickets in my sprint to stop using @poohitan's fork and switch back to your repo, but we gotta get some promise support in here first.

**Comment by kimroen** [comment]
Thanks again for this, I'll merge it shortly (I'll need to update the documentation, and I don't have time to do that right now).

I'll handle the Fastboot side of it separately, there are other issues unrelated to this that will need resolving either way.

**Comment by poohitan** [comment]
Hey @kimroen, I've just added a new section to docs. Please check if it's ok or I need to change or supplement it. Appreciate anyone's help :)

**Comment by kimroen** [comment]
Thank you again very much! There are some spelling mistakes and other things in there that I'd like to fix, but I'll merge it in as it is and work on it a bit separately.

It's a great starting point, and I really appreciate it ❤️

**Comment by offirgolan** [comment]
@kimroen any chance you can cut a release with this feature? 🙏

**Comment by kimroen** [comment]
@offirgolan Yes, but I need to land this PR first so it doesn't stop working in FastBoot: https://github.com/kimroen/ember-cli-document-title/pull/60

That PR is blocked by getting the tests set up properly: https://github.com/kimroen/ember-cli-document-title/pull/62

If you have ideas for workarounds to that problem I'm all ears!

**Comment by offirgolan** [comment]
Ah no worries at all. I'll just point to that commit for now. 

> That PR is blocked by getting the tests set up properly: #62
If you have ideas for workarounds to that problem I'm all ears!

I wish I can be of help here but I have yet to play around with fastboot. I suggest asking some question on the fastboot channel in slack though. I'm sure the mods on there can help you a lot more than I can.

**Comment by kimroen** [comment]
It's not a FastBoot-specific issue, the problem is about the test setup, so it's more of an ember-cli and node issue. Feel free to follow the links to various issues and check it out - you might have an idea of what you'd want to see.

Thanks for the suggestion!

**Pull request merged**
