### PR TITLE
Use newer private `_router` when available. Fixes #71.

### LINKED ISSUE #71: Deprecation warning starting with Ember 3.1
After updating to Ember 3.1 I've seen the following deprecation warning in our test suite logs:

> DEPRECATION: Route#router is an intimate API that has been renamed to Route#_router. However you might want to consider using the router service [deprecation id: ember-routing.route-router] See https://emberjs.com/deprecations/v3.x#toc_ember-routing-route-router for more details.

It appears to be related to the use of `self.router` at https://github.com/kimroen/ember-cli-document-title/blob/4c3d7c282c39bfc099ebf11a74be713809007691/vendor/document-title/document-title.js#L75

### PR DESCRIPTION
**Pull request by btecu**
Fixes deprecations on `Ember 3.1+`

### CODE REVIEW

**Comment by Turbo87** [comment]
we should be aware that this is a temporary fix and might fail in the future. it will get rid of the deprecation warnings but it's still using a private API that might fail at any point.

**Comment by btecu** [comment]
Correct. The real fix here is a major revamp of the entire component where it doesn't have to support 1.13.
It can be versioned properly so it doesn't break people's applications.

However, that's @kimroen decision to make.

**Comment by willviles** [comment]
@kimroen a merge and bump would be appreciated! 👋

**Comment by Duder-onomy** [comment]
@kimroen Ping-pong ^

**Comment by raghuvaran** [comment]
Can someone merge this PR please?
@kimroen

**Comment by jfelipe** [comment]
@kimroen can you please merge this? or is there any blocker?

**Comment by morgano86** [comment]
Please merge, i don't like the warnings :+1:

**Comment by mike-north** [comment]
> we should be aware that this is a temporary fix and might fail in the future. it will get rid of the deprecation warnings but it's still using a private API that might fail at any point.

I've implemented #75 which obtains the router from the container instead of using a private or intimate api.

**Comment by panthony** [comment]
Would love to see this merged.

Me and my goldfish memory spent yet again too much times tracking down where this router deprecation was coming from which, again, lead me here 🐠

**Comment by mike-north** [comment]
@panthony I've published an up-to-date fork https://github.com/mike-north/ember-cli-document-title-northm that includes this fix

**Comment by snewcomer** [comment]
Fixed in 1.0!

**Pull request closed without merging**
